apiVersion: v1
kind: Template
metadata:
  name: rocketgate-dc-templates
labels:
  template: rocketgate
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}${SUFFIX}
  spec:
    minReadySeconds: 20 # should be ready for atleast 20 seconds before the container is considered available. This will allow us
    # to catch any errors on deploy before they are available to the web
    replicas: 3
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
          memory: '128Mi'
        limits:
          cpu: '200m'
          memory: '256Mi'
    template:
      metadata:
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${VERSION}
          name: rocketgate
          ports:
          - containerPort: 4000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
          env:
          - name: ROCKETCHAT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: rocketgate-credentials
                key: token
          - name: ROCKETCHAT_USER_ID
            valueFrom:
              secretKeyRef:
                name: rocketgate-credentials
                key: userId
          - name: ROCKETCHAT_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: rocketgate-config
                key: rocketChatURL
          - name: ROCKETCHAT_ROOM_IDS
            valueFrom:
              configMapKeyRef:
                name: rocketgate-config
                key: rocketChatRooms
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rocketgate
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: web
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/disable_cookies: 'true'
    name: ${NAME}${SUFFIX}
  spec:
    host:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ConfigMap
  metadata:
      name: rocketgate-config
  stringData:
    rocketChatRooms: ${ROCKETCHAT_ROOM_IDS}
    rocketChatURL: ${ROCKETCHAT_BASE_URL}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: rocketgate
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST
  required: false
  value: ''
- description: Base URL of the Rocket.Chat instance to be searched
  displayName: Rocket.Chat Base URL
  name: ROCKETCHAT_BASE_URL
  required: true
  value: "https://chat.pathfinder.gov.bc.ca/api/v1/"
- description: Rocket.Chat rooms to search
  displayName: The ids of the Rocket.Chat rooms to be searched
  name: ROCKETCHAT_ROOM_IDS
  required: true
  value: "HfFxBfikEcpnivv4Q"