kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Secret
    stringData:
      token: ${TOKEN}
      userId: ${USER_ID}
    metadata:
      labels:
        group: ${NAME}
        component: ${NAME}-imagestream
      name: ${NAME}-credentials
parameters:
- name: NAME
  value: rocketgate
- name: TOKEN
  displayName: Rocketchat Auth Token
  required: true 
- name: USER_ID
  display: User Id
  require: true